export const tasks = [
  {
    id: 1,
    date: "01.01.23",
    theme: "Wed Design",
    title: "Название задачи",
    name: "Без статуса",
    themeStyle: "_orange",
  },
  {
    id: 2,
    date: "05.02.23",
    theme: "Research",
    title: "Название задачи",
    name: "Нужно сделать",
    themeStyle: "_green",
  },
  {
    id: 3,
    date: "13.03.23",
    theme: "Сopywriting",
    title: "Название задачи",
    name: "В работе",
    themeStyle: "_purple",
  },
  {
    id: 4,
    date: "15.04.23",
    theme: "Research",
    title: "Название задачи",
    name: "Тестирование",
    themeStyle: "_green",
  },
  {
    id: 5,
    date: "21.05.23",
    theme: "Сopywriting",
    title: "Название задачи",
    name: "Готово",
    themeStyle: "_purple",
  },
  {
    id: 6,
    date: "29.09.23",
    theme: "Research",
    title: "Название задачи1",
    name: "Нужно сделать",
    themeStyle: "_green",
  },
];
